"""
Django settings for document_generator project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from typing import List

import environ
import os
import boto3
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django_sso.sso_service.backend import acceptor, EventAcceptor

from .settings_base import *
from infra import backend, postgres, redis, storage
import launchflow as lf
from . import env_values


# ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1", ".cpl.planetwealth.com"]
ALLOWED_HOSTS = [".dc.planetwealth.com", "0.0.0.0"]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {"default": (postgres.django_settings())}

# Fetches the information for the GCS bucket and populates the django-storages settings
GS_BUCKET_NAME = storage.outputs().bucket_name
# django-storages requires service account credentials instead of user credentials
GS_CREDENTIALS = lf.gcp.utils.get_service_account_credentials()
GS_PROJECT_ID = os.getenv("GCP_PROJECT")

CACHES = {"default": redis.django_settings()}

MEDIA_URL = f"https://storage.googleapis.com/{storage.outputs().bucket_name}/media/"
STATIC_URL = "/static/"


# SSO Settings, must be called after env_values are loaded
SSO = {
    "ROOT": os.getenv("SSO_ROOT_URL"),
    "TOKEN": os.getenv("SSO_TOKEN"),
    "EVENT_ACCEPTOR_CLASS": "generator_app.middleware.SSOEventAcceptor",
}

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

STRIPE_STAGING_LEVEL_ZERO_PROD = os.getenv("STRIPE_STAGING_LEVEL_ZERO_PROD", None)
STRIPE_STAGING_LEVEL_ONE_PROD = os.getenv("STRIPE_STAGING_LEVEL_ONE_PROD", None)
STRIPE_STAGING_LEVEL_TWO_PROD = os.getenv("STRIPE_STAGING_LEVEL_TWO_PROD", None)
STRIPE_STAGING_LEVEL_THREE_PROD = os.getenv("STRIPE_STAGING_LEVEL_THREE_PROD", None)

GS_BUCKET_NAME = os.getenv('GS_BUCKET_NAME')
GCS_ENV_FOLDER = os.getenv('GCS_ENV_FOLDER')