# Generated by Django 5.0.1 on 2024-01-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0004_rename_parent_category_parent_catgory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_catgory',
            new_name='parent_category',
        ),
    ]
