# Generated by Django 5.0.1 on 2024-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0006_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='html',
            field=models.TextField(null=True),
        ),
    ]
