# Generated by Django 5.0.1 on 2024-01-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0008_userdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Section', max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator_app.template')),
            ],
        ),
    ]
