# Generated by Django 5.0.1 on 2024-01-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0009_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Text of the question')),
                ('placeholder', models.CharField(help_text='Place holder of the question', max_length=200)),
                ('question_type', models.CharField(choices=[('text', 'text'), ('radio', 'radio')], default='text', max_length=20)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='generator_app.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator_app.section')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator_app.template')),
            ],
        ),
    ]
