# Generated by Django 5.0.1 on 2024-01-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0010_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='Text of the answer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator_app.question')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator_app.section')),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator_app.userdocument')),
            ],
        ),
    ]
