# Generated by Django 5.0.1 on 2024-01-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0011_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Text of the option')),
                ('next_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options_child_question', to='generator_app.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_question', to='generator_app.question')),
            ],
        ),
    ]
