# Generated by Django 5.0.1 on 2024-02-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0015_section_parent_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='next_question',
        ),
        migrations.AddField(
            model_name='option',
            name='child_questions',
            field=models.ManyToManyField(blank=True, related_name='options_child_question', to='generator_app.question'),
        ),
    ]
