# Generated by Django 5.0.1 on 2024-02-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0018_rename_template_file_path_template_template_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocument',
            name='html',
        ),
        migrations.AddField(
            model_name='userdocument',
            name='template_file_name',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
