# Generated by Django 5.0.1 on 2024-03-09 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0019_remove_userdocument_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='generator_app.question'),
        ),
    ]
