# Generated by Django 5.0.1 on 2024-04-08 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0028_section_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
