# Generated by Django 5.0.1 on 2024-04-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0030_option_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sequence_id',
            field=models.IntegerField(default=0),
        ),
    ]
