# Generated by Django 5.0.1 on 2024-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0031_section_sequence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sequence_id',
            field=models.IntegerField(default=0),
        ),
    ]
