# Generated by Django 5.0.1 on 2024-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0034_template_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='vimeo_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
