# Generated by Django 5.0.1 on 2024-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0035_section_vimeo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='is_synced',
            field=models.BooleanField(default=True),
        ),
    ]
