# Generated by Django 5.0.1 on 2024-07-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0039_alter_template_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='last_modified',
            field=models.DateTimeField(blank=True, db_column='last_modified', null=True),
        ),
    ]
