# Generated by Django 5.0.1 on 2024-07-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0040_template_created_at_template_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('multiple', 'multiple'), ('date', 'date'), ('percentage', 'percentage'), ('image', 'image'), ('single_checkbox', 'single_checkbox'), ('currency', 'currency')], default='text', max_length=20),
        ),
    ]
