# Generated by Django 5.0.1 on 2024-08-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0041_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sequence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='sequence_id',
            field=models.IntegerField(default=0),
        ),
    ]
