# Generated by Django 5.0.1 on 2024-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator_app", "0044_customuser_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="expiration_date",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
