# Generated by Django 5.0.1 on 2024-09-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0045_alter_customuser_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='vimeo_timestamp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='vimeo_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
