# Generated by Django 5.0.1 on 2024-11-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0047_question_vimeo_link_question_vimeo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='doc_placeholders',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
