# Generated by Django 5.0.1 on 2024-01-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0003_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parent_catgory',
        ),
    ]
