# Generated by Django 5.0.1 on 2024-02-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options_child_question', to='smartdocs_app.question'),
        ),
    ]
