# Generated by Django 5.0.1 on 2024-02-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0014_alter_option_next_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='parent_section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='smartdocs_app.section'),
        ),
    ]
