# Generated by Django 5.0.1 on 2024-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0016_remove_option_next_question_option_child_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='html',
        ),
        migrations.AddField(
            model_name='template',
            name='template_file_path',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
