# Generated by Django 5.0.1 on 2024-02-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0017_remove_template_html_template_template_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='template_file_path',
            new_name='template_file_name',
        ),
    ]
