# Generated by Django 5.0.1 on 2024-03-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0020_alter_question_parent_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='parent_section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='smartdocs_app.section'),
        ),
    ]
