# Generated by Django 5.0.1 on 2024-03-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0021_alter_section_parent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='AI_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='helping_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_AI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='primary_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
