# Generated by Django 5.0.1 on 2024-03-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0022_question_ai_prompt_question_helping_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='AI_prompt',
            new_name='ai_prompt',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='is_AI',
            new_name='is_ai',
        ),
    ]
