# Generated by Django 5.0.1 on 2024-03-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0023_rename_ai_prompt_question_ai_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='primary_prompt',
        ),
        migrations.AddField(
            model_name='question',
            name='na_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
