# Generated by Django 5.0.1 on 2024-03-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0024_remove_question_primary_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('multiple', 'multiple'), ('date', 'date'), ('percentage', 'percentage'), ('image', 'image')], default='text', max_length=20),
        ),
    ]
