# Generated by Django 5.0.1 on 2024-03-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0025_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartdocs_app.template'),
        ),
    ]
