# Generated by Django 5.0.1 on 2024-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0029_alter_template_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
