# Generated by Django 5.0.1 on 2024-06-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0036_userdocument_is_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('multiple', 'multiple'), ('date', 'date'), ('percentage', 'percentage'), ('image', 'image'), ('single_checkbox', 'single_checkbox')], default='text', max_length=20),
        ),
    ]
