# Generated by Django 5.0.1 on 2024-06-20 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0037_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='stripe_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('expiry_date', models.DateTimeField()),
                ('access_level', models.CharField(choices=[('no-subscription', 'No Subscription'), ('level-0', 'Level 0'), ('level-1', 'Level 1'), ('level-2', 'Level 2'), ('level-3', 'Level 3')], default='no-subscription', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
