# Generated by Django 5.0.1 on 2024-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0038_stripe_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='access_level',
            field=models.CharField(choices=[('free', 'Level 0'), ('level-1', 'Level 1'), ('level-2', 'Level 2'), ('level-3', 'Level 3')], default='free', max_length=256),
        ),
    ]
