# Generated by Django 5.0.1 on 2024-08-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartdocs_app", "0042_category_sequence_id_template_sequence_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("level-0", "level-0"),
                    ("level-1", "level-1"),
                    ("level-2", "level-2"),
                    ("level-3", "level-3"),
                ],
                default="level-0",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
    ]
