# Generated by Django 5.0.1 on 2024-10-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs_app', '0046_section_vimeo_timestamp_alter_section_vimeo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vimeo_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='vimeo_timestamp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
