from .login import *
from .categories import *
from .document import *
from .user_dashboard import *
from .review import *
from .progress import *
from .document_download import *
from .admin_categories import *
from .admin_document import *
from .admin_users_management import *
from .user_profile import *
